# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/2

pool:
  vmImage: ubuntu-latest


stages: 
- stage: build
  jobs:
  - job: build

    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      
- stage: deploy
  jobs: 
  - job: deploy
    
    steps: 
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
        allowPartiallySucceededBuilds:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.ArtifactsDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: S3Upload@1
      inputs:
        awsCredentials: 'aws-service-conn'
        regionName: 'us-west-1'
        bucketName: 'youtube-clone-articat'
        sourceFolder: '$(Build.ArtifactStagingDirectory)'
        globExpressions: '*.zip'
        
### Deploy to AWS lambda service  
    # - task: BeanstalkDeployApplication@1
    #   inputs:
    #     awsCredentials: 'aws-service-conn'
    #     regionName: 'us-west-1'
    #     applicationName: 'youtube-clone'
    #     environmentName: 'youtube-clone'
    #     applicationType: 'version'
    


